# Generated by Django 6.0.1 on 2026-02-04 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('paragraph', 'Parágrafo'), ('paragraph_with_image', 'Parágrafo com imagem'), ('subtitle', 'Subtítulo'), ('hr', 'Separador horizontal'), ('image', 'Imagem'), ('title', 'Título'), ('carousel', 'Carrossel'), ('youtube', 'Vídeo YouTube')], max_length=31, verbose_name='Tipo')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Bloco de conteúdo',
                'verbose_name_plural': 'Blocos de conteúdo',
                'ordering': ('related_post', 'order'),
            },
        ),
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/blocks/', verbose_name='Imagem')),
                ('captions', models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Legenda')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texto acessibilidade')),
                ('credits', models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Fotógrafo/Créditos')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='portal.newsblock')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Titulo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Thumbnail')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('draft', models.BooleanField(default=False, verbose_name='Rascunho')),
                ('portal', models.CharField(choices=[('portal_inovai', 'Portal Inovaí'), ('portal_mulheres_ciencia', 'Portal Meninas e Mulheres na Ciência')], default='portal_inovai', max_length=31, verbose_name='Portal')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ('-publish_date',),
            },
        ),
        migrations.AddField(
            model_name='newsblock',
            name='related_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='portal.newspost'),
        ),
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Título')),
                ('image', models.ImageField(upload_to='destaques', verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('portal', models.CharField(choices=[('portal_inovai', 'Portal Inovaí'), ('portal_mulheres_ciencia', 'Portal Meninas e Mulheres na Ciência')], default='portal_inovai', max_length=31, verbose_name='Portal')),
                ('points_to_noticia', models.BooleanField(default=False, verbose_name='Aponta para notícia')),
                ('link_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de destino')),
                ('button_color', models.CharField(default='#0d6efd', max_length=15, validators=[django.core.validators.RegexValidator(message='Cor inválida. Use formato hexadecimal (ex: #FFFFFF ou #FFF).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor do botão')),
                ('button_text', models.CharField(default='Saiba mais', max_length=127, verbose_name='Texto do botão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='portal.newspost')),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
                'ordering': ('-created_at',),
            },
        ),
    ]
