# Generated by Django 6.0.1 on 2026-01-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to=None, verbose_name='Imagem de apresentação')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Imagem de conteudo')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('publish_date', models.DateField(verbose_name='Data de publicação')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ('-publish_date',),
            },
        ),
    ]
