# Generated by Django 6.0.1 on 2026-02-03 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockimage',
            name='image',
            field=models.ImageField(upload_to='news/blocks/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='block_type',
            field=models.CharField(choices=[('paragraph', 'Parágrafo'), ('paragraph_with_image', 'Parágrafo com imagem'), ('subtitle', 'Subtítulo'), ('hr', 'Separador horizontal'), ('image', 'Imagem'), ('title', 'Título'), ('carousel', 'Carrossel')], max_length=31, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Thumbnail'),
        ),
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Título')),
                ('image', models.ImageField(upload_to='destaques', verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('portal', models.CharField(choices=[('portal_inovai', 'Portal Inovaí'), ('portal_mulheres_ciencia', 'Portal Meninas e Mulheres na Ciência')], default='portal_inovai', max_length=31, verbose_name='Portal')),
                ('points_to_noticia', models.BooleanField(default=False, verbose_name='Aponta para notícia')),
                ('link_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de destino')),
                ('button_color', models.CharField(default='#FFFFFF', max_length=15, validators=[django.core.validators.RegexValidator(message='Cor inválida. Use formato hexadecimal (ex: #FFFFFF ou #FFF).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor do botão')),
                ('button_text', models.CharField(default='Saiba mais', max_length=127, verbose_name='Texto do botão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='portal.newspost')),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
                'ordering': ('-created_at',),
            },
        ),
    ]
