# Generated by Django 6.0.1 on 2026-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='block_type',
            field=models.CharField(choices=[('paragraph', 'Parágrafo'), ('paragraph_with_image', 'Parágrafo com imagem'), ('subtitle', 'Subtítulo'), ('hr', 'Separador horizontal'), ('image', 'Imagem'), ('title', 'Título'), ('carousel', 'Carrossel')], max_length=31, verbose_name='Tipo'),
        ),
    ]
