# Generated by Django 6.0.1 on 2026-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_blockimage_image_alter_newsblock_block_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Rascunho'),
        ),
    ]
