# Generated by Django 6.0.1 on 2026-02-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_newspost_active_newspost_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsblock',
            options={'ordering': ('related_post', 'order'), 'verbose_name': 'Bloco de conteúdo', 'verbose_name_plural': 'Blocos de conteúdo'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
    ]
