# Generated by Django 6.0.1 on 2026-02-04 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_newsblock_options_alter_newspost_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaque',
            name='button_color',
            field=models.CharField(default='#0d6efd', max_length=15, validators=[django.core.validators.RegexValidator(message='Cor inválida. Use formato hexadecimal (ex: #FFFFFF ou #FFF).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor do botão'),
        ),
    ]
