# Generated by Django 6.0.1 on 2026-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_newsblock_options_alter_newspost_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='portal',
            field=models.CharField(choices=[('portal_inovai', 'Portal Inovaí'), ('portal_mulheres_ciencia', 'Portal Meninas e Mulheres na Ciência')], default='portal_inovai', max_length=31, verbose_name='Portal'),
        ),
    ]
