# Generated by Django 6.0.1 on 2026-02-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_destaque_button_color'),
        ('portal', '0005_newspost_portal'),
    ]

    operations = [
    ]
