# Generated by Django 6.0.1 on 2026-02-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_newsblock_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(upload_to='attachments/', verbose_name='Arquivo')),
                ('captions', models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Legenda')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texto acessibilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.newsblock')),
            ],
        ),
    ]
